{:tag ...     ; <1>
 :attrs ...
 :content
 [{:tag ... :attrs ... :content [...]}
  ...
  {:tag ...
   :attrs ...
   :content
   [{:tag ... :attrs ... :content [...]}
    ...
    {:tag ... :attrs ... :content [...]}]}]}